// Enable Driver
// #define CONFIG_DRIVER_ENABLE 1

// Enable AT
// #define CONFIG_AT_ENABLE 1
// #define CONFIG_AT_DEVNAME "atdev"
// #define CONFIG_AT_OOBTABLEN 6
// #define CONFIG_AT_RECVMAXLEN 1024
// #define CONFIG_AT_TASKPRIOR 10

// Enable OS
#define CONFIG_LITEOS_ENABLE 1
//#define CONFIG_FREERTOS_ENABLE 1
//#define CONFIG_OPENHARMONYOS_ENABLE 1 

#define CONFIG_LINKLOG_ENABLE 1
#define CONFIG_LINKQUEUE_ENABLE 1

// Enable Shell
// #define CONFIG_SHELL_ENABLE 1
// #define CONFIG_SHELL_TASK_STACKSIZE 2048
// #define CONFIG_SHELL_TASK_PRIOR 10

// Enable Demo
#define CONFIG_LINKDEMO_ENABLE 1
#define CONFIG_USER_DEMO "oc_mqtt_demo"

// Enable NB-IoT
//#define CONFIG_BOUDICA150_ENABLE 1

// Enable LWM2M
/*
#define CONFIG_OCLWM2M_ENABLE 1
#define CONFIG_OCLWM2MTINY_ENABLE 1
#define CONFIG_LWM2M_AL_ENABLE 1
#define CONFIG_WAKAAMALWM2M_ENABLE 1
*/

// Enable CoAP
/*
#define CONFIG_OCCOAP_ENABLE 1
#define CONFIG_COAP_AL_ENABLE 1
#define CONFIG_LITECOAP_ENABLE 1
#define CONFIG_OCCOAPTINY_ENABLE 1
*/

// Enable TCPIP
#define CONFIG_TCPIP_AL_ENABLE 1

// Enbale ESP8266 根据自己的网络环境配置
#define CONFIG_ESP8266_ENABLE 1
#define CONFIG_ESP8266_SSID "AngelStar"
#define CONFIG_ESP8266_PWD "xingli27"

// Enable MQTT
#define CONFIG_CJSON_ENABLE 1
#define CONFIG_MQTT_AL_ENABLE 1
#define CONFIG_PAHO_MQTT 1
#define CONFIG_OCMQTT_ENABLE 1
#define CONFIG_OCMQTT_ATCMD 1
#define CONFIG_OC_MQTT_V5 1
#define CONFIG_OC_TINYMQTTV5_ENABLE 1
#define CONFIG_OC_MQTTV5_PROFILE 1

// MQTT Configuration
#define CONFIG_PAHO_CONNECT_TIMEOUT 10000
#define CONFIG_PAHO_CMD_TIMEOUT 10000
#define CONFIG_PAHO_LOOPTIMEOUT 10
#define CONFIG_PAHO_SNDBUF_SIZE 2048
#define CONFIG_PAHO_RCVBUF_SIZE 2048

/*DTLS*/
#define CONFIG_DTLS_AL_ENABLE 1
#define CONFIG_MBEDTLS_ENABLE 1
#define CONFIG_MBEDTLS_PSK 1

// Enable iot_config.h
#define CONFIG_IOT_LINK_CONFIGFILE "iot_config.h"

// Enable message storage in abnormal scene demo
#define CONFIG_MSG_STORAGE_ABNORMAL_SCENE_DEMO

