sudo: true
language: c

compiler:
  - gcc

os:
  - linux

sudo: required

before_install:
  - ./travis-install.sh

script:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./travis-build.sh; fi

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - cmake
      - cmake-data
      - mosquitto
      - doxygen


