# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ota_package_tool_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 383)
        Form.setMinimumSize(QtCore.QSize(600, 383))
        Form.setMaximumSize(QtCore.QSize(600, 383))
        Form.setProperty("unifiedTitleAndToolBarOnMac", False)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setGeometry(QtCore.QRect(4, 0, 591, 371))
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 571, 71))
        self.groupBox.setObjectName("groupBox")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(30, 33, 54, 12))
        self.label_29.setObjectName("label_29")
        self.generate_key_button = QtWidgets.QPushButton(self.groupBox)
        self.generate_key_button.setGeometry(QtCore.QRect(464, 36, 91, 23))
        self.generate_key_button.setObjectName("generate_key_button")
        self.algoComboBox = QtWidgets.QComboBox(self.groupBox)
        self.algoComboBox.setGeometry(QtCore.QRect(90, 27, 141, 22))
        self.algoComboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.algoComboBox.setObjectName("algoComboBox")
        self.algoComboBox.addItem("")
        self.generate_package_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.generate_package_groupbox.setGeometry(QtCore.QRect(10, 10, 571, 271))
        self.generate_package_groupbox.setObjectName("generate_package_groupbox")
        self.oldfile_line_edit = QtWidgets.QLineEdit(self.generate_package_groupbox)
        self.oldfile_line_edit.setEnabled(True)
        self.oldfile_line_edit.setGeometry(QtCore.QRect(114, 119, 441, 20))
        self.oldfile_line_edit.setAcceptDrops(True)
        self.oldfile_line_edit.setObjectName("oldfile_line_edit")
        self.import_newfile_button = QtWidgets.QPushButton(self.generate_package_groupbox)
        self.import_newfile_button.setGeometry(QtCore.QRect(20, 147, 75, 23))
        self.import_newfile_button.setObjectName("import_newfile_button")
        self.import_sota_json_file_button = QtWidgets.QPushButton(self.generate_package_groupbox)
        self.import_sota_json_file_button.setEnabled(True)
        self.import_sota_json_file_button.setGeometry(QtCore.QRect(20, 180, 141, 23))
        self.import_sota_json_file_button.setCheckable(False)
        self.import_sota_json_file_button.setObjectName("import_sota_json_file_button")
        self.diff_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.diff_radio_button.setGeometry(QtCore.QRect(100, 58, 89, 16))
        self.diff_radio_button.setChecked(True)
        self.diff_radio_button.setObjectName("diff_radio_button")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.diff_radio_button)
        self.newfile_line_edit = QtWidgets.QLineEdit(self.generate_package_groupbox)
        self.newfile_line_edit.setGeometry(QtCore.QRect(114, 149, 441, 20))
        self.newfile_line_edit.setObjectName("newfile_line_edit")
        self.sota__fota_label = QtWidgets.QLabel(self.generate_package_groupbox)
        self.sota__fota_label.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.sota__fota_label.setObjectName("sota__fota_label")
        self.all_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.all_radio_button.setGeometry(QtCore.QRect(190, 58, 89, 16))
        self.all_radio_button.setObjectName("all_radio_button")
        self.buttonGroup_2.addButton(self.all_radio_button)
        self.import_oldfile_button = QtWidgets.QPushButton(self.generate_package_groupbox)
        self.import_oldfile_button.setGeometry(QtCore.QRect(20, 117, 75, 23))
        self.import_oldfile_button.setObjectName("import_oldfile_button")
        self.sota_json_file_line_edit = QtWidgets.QLineEdit(self.generate_package_groupbox)
        self.sota_json_file_line_edit.setGeometry(QtCore.QRect(174, 181, 381, 20))
        self.sota_json_file_line_edit.setObjectName("sota_json_file_line_edit")
        self.sota_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.sota_radio_button.setGeometry(QtCore.QRect(100, 30, 89, 16))
        self.sota_radio_button.setChecked(True)
        self.sota_radio_button.setObjectName("sota_radio_button")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.sota_radio_button)
        self.file_type_label = QtWidgets.QLabel(self.generate_package_groupbox)
        self.file_type_label.setGeometry(QtCore.QRect(21, 58, 61, 16))
        self.file_type_label.setObjectName("file_type_label")
        self.fota_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.fota_radio_button.setGeometry(QtCore.QRect(190, 30, 89, 16))
        self.fota_radio_button.setObjectName("fota_radio_button")
        self.buttonGroup.addButton(self.fota_radio_button)
        self.sign_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.sign_radio_button.setGeometry(QtCore.QRect(101, 83, 89, 16))
        self.sign_radio_button.setChecked(True)
        self.sign_radio_button.setObjectName("sign_radio_button")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.sign_radio_button)
        self.unsign_radio_button = QtWidgets.QRadioButton(self.generate_package_groupbox)
        self.unsign_radio_button.setGeometry(QtCore.QRect(190, 83, 89, 16))
        self.unsign_radio_button.setObjectName("unsign_radio_button")
        self.buttonGroup_3.addButton(self.unsign_radio_button)
        self.sign_label = QtWidgets.QLabel(self.generate_package_groupbox)
        self.sign_label.setGeometry(QtCore.QRect(20, 83, 61, 16))
        self.sign_label.setObjectName("sign_label")
        self.private_key_line_edit = QtWidgets.QLineEdit(self.generate_package_groupbox)
        self.private_key_line_edit.setGeometry(QtCore.QRect(124, 210, 431, 21))
        self.private_key_line_edit.setText("")
        self.private_key_line_edit.setObjectName("private_key_line_edit")
        self.import_key_button = QtWidgets.QPushButton(self.generate_package_groupbox)
        self.import_key_button.setGeometry(QtCore.QRect(20, 210, 91, 23))
        self.import_key_button.setObjectName("import_key_button")
        self.generate_package_button = QtWidgets.QPushButton(self.generate_package_groupbox)
        self.generate_package_button.setGeometry(QtCore.QRect(445, 240, 111, 23))
        self.generate_package_button.setObjectName("generate_package_button")

        self.retranslateUi(Form)
        self.sota_radio_button.toggled['bool'].connect(Form.sota_radio_toggled)
        self.sign_radio_button.toggled['bool'].connect(Form.sign_radio_toggled)
        self.diff_radio_button.toggled['bool'].connect(Form.diff_radio_toggled)
        self.generate_key_button.clicked.connect(Form.generate_key_pares)
        self.import_oldfile_button.clicked.connect(Form.import_oldfile)
        self.import_newfile_button.clicked.connect(Form.import_newfile)
        self.import_sota_json_file_button.clicked.connect(Form.import_json_file)
        self.import_key_button.clicked.connect(Form.import_private_key)
        self.generate_package_button.clicked.connect(Form.generate_package)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "华为离线软固件升级包制作工具"))
        self.groupBox.setTitle(_translate("Form", "生成数字签名公私钥对"))
        self.label_29.setText(_translate("Form", "算法"))
        self.generate_key_button.setText(_translate("Form", "生成公私钥对"))
        self.algoComboBox.setCurrentText(_translate("Form", "RSA2048+SHA256"))
        self.algoComboBox.setItemText(0, _translate("Form", "RSA2048+SHA256"))
        self.generate_package_groupbox.setTitle(_translate("Form", "生成软固件升级包"))
        self.import_newfile_button.setText(_translate("Form", "导入新版本"))
        self.import_sota_json_file_button.setText(_translate("Form", "导入软件升级描述文件"))
        self.diff_radio_button.setText(_translate("Form", "差分"))
        self.sota__fota_label.setText(_translate("Form", "软固件升级"))
        self.all_radio_button.setText(_translate("Form", "全量"))
        self.import_oldfile_button.setText(_translate("Form", "导入旧版本"))
        self.sota_radio_button.setText(_translate("Form", "软件升级"))
        self.file_type_label.setText(_translate("Form", "文件类型"))
        self.fota_radio_button.setText(_translate("Form", "固件升级"))
        self.sign_radio_button.setText(_translate("Form", "签名"))
        self.unsign_radio_button.setText(_translate("Form", "不签名"))
        self.sign_label.setText(_translate("Form", "是否签名"))
        self.import_key_button.setText(_translate("Form", "导入签名用私钥"))
        self.generate_package_button.setText(_translate("Form", "生成升级包"))
