class mqtt_device_info(object):
    MQTT_EP_USER = "mqtt_sdk02"
    MQTT_EP_PASSWD = "4e5afee28fbf53abf31a"
    MQTT_DEVICEID = "40639a89-9dc2-4c08-8fd6-2cae69c93828"

class mqtt_testid(object):
    TEST_OC_ATINY_MQTT_INIT = 0x20000
    TEST_OC_ATINY_MQTT_CONNECT = TEST_OC_ATINY_MQTT_INIT+1
    TEST_OC_ATINY_MQTT_SUBCMD = TEST_OC_ATINY_MQTT_INIT + 2
    TEST_OC_ATINY_MQTT_REPORT = TEST_OC_ATINY_MQTT_INIT + 3
    TEST_OC_ATINY_MQTT_DISCONNECT = TEST_OC_ATINY_MQTT_INIT + 4
    TEST_OC_ATINY_MQTT_DEINIT = TEST_OC_ATINY_MQTT_INIT + 5
    TEST_MQTT_AL_INIT = 0x30000
    TEST_MQTT_AL_INSTALL = TEST_MQTT_AL_INIT + 1
    TEST_MQTT_AL_UNINSTALL = TEST_MQTT_AL_INIT + 2
    TEST_MQTT_AL_CONNECT = TEST_MQTT_AL_INIT + 3
    TEST_MQTT_AL_DISCONNECT = TEST_MQTT_AL_INIT + 4
    TEST_MQTT_AL_SUBSCRIBLE = TEST_MQTT_AL_INIT + 5
    TEST_MQTT_AL_PBULISH = TEST_MQTT_AL_INIT + 6
    TEST_MQTT_AL_CHECKSTATUS = TEST_MQTT_AL_INIT + 7
    TEST_MQTT_AL_DEINIT = TEST_MQTT_AL_INIT + 8
