# LWM2M
class lwm2m_device_info(object):
    LWM2M_EP_USER = "lwm2m_autotest_cy"
    LWM2M_EP_PASSWD = "010203040506"
    LWM2M_DEVICEID = "367889c2-5374-406c-9a69-fbb82bacde4d"
    BS_LWM2M_EP_USER = "dev1_bs_nodtls"
    BS_LWM2M_EP_PASSWD = "dc00b51cef9106a4922d"
    BS_LWM2M_DEVICEID = "d12339f9-0987-4b7a-bcc6-898290e4fafe"

class lwm2m_testid(object):
    TEST_OC_LWM2M_INIT = 0x0000
    TEST_OC_LWM2M_REGISTER = TEST_OC_LWM2M_INIT+1
    TEST_OC_LWM2M_CONFIG = TEST_OC_LWM2M_INIT+2
    TEST_OC_LWM2M_REPORT = TEST_OC_LWM2M_INIT+3
    TEST_OC_LWM2M_GETVALUE = TEST_OC_LWM2M_INIT+4
    TEST_OC_LWM2M_DECONFIG = TEST_OC_LWM2M_INIT+5
    TEST_OC_LWM2M_DEINIT = TEST_OC_LWM2M_INIT+6
    TEST_OC_LWM2M_UNREGISTER = TEST_OC_LWM2M_INIT+7
    TEST_LWM2M_AL_INSTALL = 0x10000
    TEST_LWM2M_AL_CONFIG = TEST_LWM2M_AL_INSTALL+1
    TEST_LWM2M_AL_CONNECT = TEST_LWM2M_AL_INSTALL+2
    TEST_LWM2M_AL_ADD_OBJECT = TEST_LWM2M_AL_INSTALL+3
    TEST_LWM2M_AL_SEND = TEST_LWM2M_AL_INSTALL+4
    TEST_LWM2M_AL_RECEIVE = TEST_LWM2M_AL_INSTALL+5
    TEST_LWM2M_AL_DISCONNECT = TEST_LWM2M_AL_INSTALL+6
    TEST_LWM2M_AL_DELETE_OBJECT = TEST_LWM2M_AL_INSTALL+7
    TEST_LWM2M_AL_DECONFIG = TEST_LWM2M_AL_INSTALL+8
    TEST_LWM2M_AL_UNINSTALL = TEST_LWM2M_AL_INSTALL+9


# MQTT
class mqtt_device_info(object):
    MQTT_EP_USER = "mqtt_sdk05"
    MQTT_EP_PASSWD = "2348d831419f04b39512"
    MQTT_DEVICEID = "230d351d-dc30-47ee-b1c5-2facce1d453c"
    BS_MQTT_EP_USER = "mqtt_bs001"
    BS_MQTT_EP_PASSWD = "dc00b51cef9106a4922d"
    BS_MQTT_DEVICEID = "d12339f9-0987-4b7a-bcc6-898290e4fafe"

class mqtt_testid(object):
    TEST_OC_MQTT_INIT = 0x20000
    TEST_OC_MQTT_REGISTER = TEST_OC_MQTT_INIT+1
    TEST_OC_MQTT_CONFIG = TEST_OC_MQTT_INIT+2
    TEST_OC_MQTT_JSON_FMT_REQ = TEST_OC_MQTT_INIT + 3
    TEST_OC_MQTT_JSON_FMT_RES = TEST_OC_MQTT_INIT + 4
    TEST_OC_MQTT_REPORT = TEST_OC_MQTT_INIT + 5
    TEST_OC_MQTT_DECONFIG = TEST_OC_MQTT_INIT + 6
    TEST_OC_MQTT_DEINIT = TEST_OC_MQTT_INIT + 7
    TEST_OC_MQTT_GETVALUE = TEST_OC_MQTT_INIT + 8
    TEST_MQTT_AL_INIT = 0x30000
    TEST_MQTT_AL_INSTALL = TEST_MQTT_AL_INIT + 1
    TEST_MQTT_AL_UNINSTALL = TEST_MQTT_AL_INIT + 2
    TEST_MQTT_AL_CONNECT = TEST_MQTT_AL_INIT + 3
    TEST_MQTT_AL_DISCONNECT = TEST_MQTT_AL_INIT + 4
    TEST_MQTT_AL_SUBSCRIBLE = TEST_MQTT_AL_INIT + 5
    TEST_MQTT_AL_PBULISH = TEST_MQTT_AL_INIT + 6
    TEST_MQTT_AL_CHECKSTATUS = TEST_MQTT_AL_INIT + 7
    TEST_MQTT_AL_DEINIT = TEST_MQTT_AL_INIT + 8


class coap_device_info(object):
    COAP_EP_USER = "coapTest003"
    COAP_EP_PASSWD = "010203040506"
    COAP_DEVICEID = "6aff1caa-e417-45b2-afd8-f2ceb75c6bd3"

class coap_testid(object):
    TEST_OC_COAP_INIT     = 0x40000
    TEST_OC_COAP_REGISTER = TEST_OC_COAP_INIT+1
    TEST_OC_COAP_CONFIG   = TEST_OC_COAP_INIT+2
    TEST_OC_COAP_REPORT   = TEST_OC_COAP_INIT+3
    TEST_OC_COAP_GETVALUE = TEST_OC_COAP_INIT+4
    TEST_OC_COAP_DECONFIG = TEST_OC_COAP_INIT+5
    TEST_OC_COAP_DEINIT   = TEST_OC_COAP_INIT+6