class mqtt_device_info(object):
    MQTT_EP_USER = "mqtt_sdk05"
    MQTT_EP_PASSWD = "2348d831419f04b39512"
    MQTT_DEVICEID = "230d351d-dc30-47ee-b1c5-2facce1d453c"
    BS_MQTT_EP_USER = "mqtt_bs001"
    BS_MQTT_EP_PASSWD = "dc00b51cef9106a4922d"
    BS_MQTT_DEVICEID = "d12339f9-0987-4b7a-bcc6-898290e4fafe"

class mqtt_testid(object):
    TEST_OC_MQTT_INIT = 0x20000
    TEST_OC_MQTT_REGISTER = TEST_OC_MQTT_INIT+1
    TEST_OC_MQTT_CONFIG = TEST_OC_MQTT_INIT+2
    TEST_OC_MQTT_JSON_FMT_REQ = TEST_OC_MQTT_INIT + 3
    TEST_OC_MQTT_JSON_FMT_RES = TEST_OC_MQTT_INIT + 4
    TEST_OC_MQTT_REPORT = TEST_OC_MQTT_INIT + 5
    TEST_OC_MQTT_DECONFIG = TEST_OC_MQTT_INIT + 6
    TEST_OC_MQTT_DEINIT = TEST_OC_MQTT_INIT + 7
    TEST_OC_MQTT_GETVALUE = TEST_OC_MQTT_INIT + 8
    TEST_MQTT_AL_INIT = 0x30000
    TEST_MQTT_AL_INSTALL = TEST_MQTT_AL_INIT + 1
    TEST_MQTT_AL_UNINSTALL = TEST_MQTT_AL_INIT + 2
    TEST_MQTT_AL_CONNECT = TEST_MQTT_AL_INIT + 3
    TEST_MQTT_AL_DISCONNECT = TEST_MQTT_AL_INIT + 4
    TEST_MQTT_AL_SUBSCRIBLE = TEST_MQTT_AL_INIT + 5
    TEST_MQTT_AL_PBULISH = TEST_MQTT_AL_INIT + 6
    TEST_MQTT_AL_CHECKSTATUS = TEST_MQTT_AL_INIT + 7
    TEST_MQTT_AL_DEINIT = TEST_MQTT_AL_INIT + 8
